### ISSUE TITLE
Strange diagonal screen blanking/unresponsiveness

### ISSUE THREAD

**Issue by RedshiftVelocities** [rmkit-dev/rmkit#65] opened 2021-01-24 02:39 UTC
Sometimes when I make a stroke with the pen when reMux is installed, a large diagonal region of the screen goes blank and the tablet (remarkable 1) goes unresponsive for a few seconds. I haven't been able to determine the exact circumstances that cause this. There also seems to be a related issue where after this happens, the pen will write when above (not touching) the screen.

**Comment by raisjn** [comment] 2021-01-24 02:42
what version are you on? please consider using the version from testing: https://toltec-dev.org/testing/remux_0.1.7-3_armv7-3.2.ipk 

 if it repros with that, please let me know

**Comment by raisjn** [comment] 2021-01-24 02:45
(it seems related to https://github.com/rmkit-dev/rmkit/issues/44)

**Comment by RedshiftVelocities** [comment] 2021-01-24 03:10
I have not been able reproduce the issue with the testing version. The version I was on previously was 0.1.5-1, which is the default one on Toltec.

**Comment by raisjn** [comment] 2021-01-27 02:51
duplicate of #44

**Comment by raisjn** [comment] 2021-01-29 03:34
closing this since stable no longer has this issue

**Closed by raisjn** 2021-01-29 03:34 UTC
