### ISSUE TITLE
[remux] can't launch self-compiled apps with remux from toltec testing channel

### ISSUE THREAD

**Issue by ard0gg** [rmkit-dev/rmkit#122] opened 2021-04-08 12:33 UTC
This might be related to 2.6 Compatibility which is being tracked here: [toltec-dev/toltec#322](https://github.com/toltec-dev/toltec/issues/322)

I have rebuilt Zshelf using the toltec toolchain v2.0.1. If i launch Zshelf from the command line, it will launch right away and is functional. However if I launch Zshelf from Remux, it seems to hang for a bit longer, then will eventually come up, but doesn't seem to load the book data ([See Image](https://photos.app.goo.gl/CHhBQcUD4me4eraW8)). I can click on the search button and enter text into the search field, but searches no longer work. 

I tried this using remux from ~~stable toltec as well as~~ the testing branch and rebuilding remux using the 2.0.1 toolkit with the same results. 

Any thoughts?

**Comment by raisjn** [comment] 2021-04-08 13:00
yes, i do have thoughts. cc @matteodelabre

https://github.com/toltec-dev/toltec/pull/310/ changed how rm2fb works. now the preload library is directly inserted into programs at compile time in toltec and remux doesn't have it automatically turned on for all launched programs

please switch back to stable (to return to the rm2fb shim being turned on for all apps). i will change remux to use the LD_PRELOAD (always) in the mean time.

**Comment by raisjn** [comment] 2021-04-08 13:49
now that i read your answer more closely, you say it's not because of stable v. testing. can you share your zshelf binary?

**Comment by ard0gg** [comment] 2021-04-08 13:52
I must have been mistaken. I switched back to stable branch and it worked. Sorry for confusion.

**Comment by raisjn** [comment] 2021-04-12 02:16
https://github.com/toltec-dev/toltec/pull/338 addresses this (if/when that lands in toltec testing, then remux will be able to launch custom compiled apps)

**Comment by matteodelabre** [comment] 2021-05-07 19:49
Also, to clarify, this issue is not related to the 2.6 system update.

**Comment by ralsei** [comment] 2021-06-23 01:54
I can confirm that this is a problem that's probably unrelated to rm2fb, since I'm on an rM1 and have the same behavior. This doesn't occur with remux from Toltec stable, even with the same zshelf binary.

**Comment by raisjn** [comment] 2021-06-23 12:48
how is it occurring from testing? this is surprising to be because I thought we fixed it

**Comment by matteodelabre** [comment] 2021-06-23 12:54
What system version are you on @ralsei? Also, are you using a self-compiled version of zshelf or a Toltec package? If you’re installing it from Toltec, which package version did you install?

**Comment by ralsei** [comment] 2021-06-23 14:51
I'm on 2.8.0.98, running ZShelf and remux packages from toltec-dev/toltec#366's artifacts. None of my packages are self-compiled.

Downgrading remux specifically to the version from Toltec stable makes ZShelf start fine. So it's likely this is a regression in remux, in my mind.

**Comment by matteodelabre** [comment] 2021-06-23 15:34
Thanks for the details. I’ll try to reproduce the issue this evening.

**Comment by matteodelabre** [comment] 2021-06-23 20:25
Unfortunately I can’t make ZShelf work, because the website that it’s scraping seems to have changed some of its classnames (just opened khanhas/zshelf#6 to track this). So I can’t reproduce this issue right now since I can’t log into the app.

**Comment by ralsei** [comment] 2021-06-23 20:29
ZShelf works for me on 1lib.us _and_ displays this error, so it might be unrelated.

**Comment by matteodelabre** [comment] 2021-06-23 21:05
That’s strange, I can’t get the book listing to load. I’ll investigate further.

**Comment by matteodelabre** [comment] 2021-06-23 21:27
Okay, so it seems that I can kind of reproduce the bug. Specifically, ZShelf works fine on its own, but as soon as I start remux, ZShelf won’t load (_even after I killed remux_).

**Comment by ralsei** [comment] 2021-06-23 22:04
I'm on an rM1, and ZShelf has never worked for me while launching from remux. I don't have to kill remux to get it to work though, I can launch it through the command-line fine, and books are displayed.

**Comment by matteodelabre** [comment] 2021-06-23 22:28
Alright, I’ll have to investigate on a rM1 then.

**Comment by raisjn** [comment] 2021-06-23 22:32
there's some trickiness here because you need to make sure to restart remux when switching channels. aside from that, I am unsure why zshelf in specific isn't working from the PR

**Comment by raisjn** [comment] 2021-06-24 19:55
based on offline discussion, the issue was that the environment was not properly setup and remux probably needs to add variables to its PATH before launching zshelf. not sure why it worked in stable

**Comment by ralsei** [comment] 2021-06-25 02:28
adding this file to `~/apps/` launches zshelf fine:
```sh
#!/bin/sh
export SHELL=/bin/sh
export PWD=/home/root
export HOME=/home/root
export QT_QPA_PLATFORM=epaper
export QMLSCENE_DEVICE=epaper
export USER=root
export PATH=/opt/bin:/opt/sbin:/home/root/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

zshelf
```

don't know which one of these environment variables is actually causing the issue. but it sure is one of them

**Comment by raisjn** [comment] 2021-08-16 01:25
fixed in toltec now

**Closed by raisjn** 2021-08-16 01:25 UTC
Labels: bug
