### ISSUE TITLE
Power management issues with latest rm2 patch

### ISSUE THREAD

**Issue by aedelsten** [rmkit-dev/rmkit#124] opened 2021-04-24 19:18 UTC
I am experiencing odd power management problems with remux installed on my rm2 with the latest patch (`uname -a` is `Linux reMarkable 4.14.78 #1 SMP PREEMPT Tue Feb 23 20:05:57 UTC 2021 armv7l GNU/Linux`). 

I have entware/Toltec installed and installed rm2fb, koreader and remux using Toltec/opkg.

I also have ddvk-hacks installed but did that manually (not sure it's relevant but want to mention) .

Upon a fresh boot (into xochitl) the device functions as normal. If I ssh to the device and am on the main home screen, `top` reports no processes taking other than 0%. Loading a notebook briefly pops xochitl and remarkable-shutdown up to 30-40% for a few seconds then everything goes back to 0%.

Swiping up from bottom-right properly displays the remux menu. If I choose KOReader (which is listed twice (?), both entries work), KOreader opens and works correctly. The `{reader.lua}` is reported as using 13% of RAM and is generally 0% when the page is static and about 3-5% CPU when turning a page (remarkable-shutdown pops to about 30% CPU when swiping).

The problems then start. If I leave koreader in the foreground for a while (15-30 minutes) when switching back to "remarkable" from the remux menu xochitl has gone to sleep. Similarly if I go from xochitl to koreader and straight back, then wait 15-30 minutes, then switch to koreader, the koreader sometimes also "goes to sleep". 

Also, after doing this transition (boot->xochitl -> koreader -> xochitl) the device idle and sleeping gets very weird. While in xochitl, sometimes it doesn't sleep at all (even if you leave it for an hour or so). Other times it sleeps but the screen doesn't change at all (swipes, stylus, ssh stop working and you have to press the power button to get them going again). Other times it goes to sleep with a full screen blank and "remarkable is sleeping" right in the middle of the screen. And yet other times, the main screen you were last on remains but the black device sleeping strip across the top appears. 

Battery usage also seems high under general daily use (taking some notes, leave for a 30 mins, take a few more, actually tap power to sleep it, use again in another 30 etc). And last night I could have sworn I hard powered off (held down power and pressed the "turn off" button) and this morning there's a warning that only 8% battery remains. It was fully charged yesterday.

If you need any more testing or logs etc let me know.

**Comment by raisjn** [comment] 2021-04-24 19:31
thanks for reporting! which version of remux are you on? i suggest using a newer version (https://opkg.rmkit.dev/testing/ - can use a download link for remux), but overall i recommend disabling remux power management for now (see the README for how to) as the overall issue is that each app has its own sleep timer and remux also has one. 

for the battery usage: i have a program for keeping track of battery usage (and app usage), but i think it is likely related to the sleep systems getting messed up.

**Comment by aedelsten** [comment] 2021-04-24 19:51
I'll give the newer version from testing a go and disable power. 

Forgive me, I can't actually find anything on power configuration in the README. You mean the README.md on github or somewhere else?

Also, I switched over to "https://toltec-dev.org/testing/" in the opkg.conf and am getting an error. 
```reMarkable: ~/ vim /opt/etc/opkg.conf
reMarkable: ~/ opkg update
Downloading https://bin.entware.net/armv7sf-k3.2/Packages.gz
Updated list of available packages in /opt/var/opkg-lists/entware
Downloading https://toltec-dev.org/testing/Packages.gz
*** Failed to download the package list from https://toltec-dev.org/testing/Packages.gz

Collected errors:
 * opkg_download: Failed to download https://toltec-dev.org/testing/Packages.gz, wget returned 8.
```
I get the same 404 from a standard web browser (/stable/Packages.gz" works fine). I will try again later.

**Comment by Eeems** [comment] 2021-04-24 21:02
I believe the new testing url for rM2 is https://toltec-dev.org/testing/rm2

**Comment by raisjn** [comment] 2021-04-24 23:37
> Also, I switched over to "https://toltec-dev.org/testing/" in the opkg.conf and am getting an error.

i don't recommend switching just yet, just grabbing the remux package from opkg.rmkit.dev (https://opkg.rmkit.dev/testing/remux_0.1.9-1_armv7-3.2.ipk), but up to you

> Forgive me, I can't actually find anything on power configuration in the README. You mean the README.md on github or somewhere else?

yes, in https://github.com/rmkit-dev/rmkit/tree/master/src/remux, it describes `manage_power` setting to place in remux.conf

**Comment by aedelsten** [comment] 2021-04-25 21:12
Thanks guys. I have installed just the remux package and also have:

```
reMarkable: ~/ cat /home/root/.config/remux/remux.conf
manage_power=false
```

I'll report back in a few days on general battery usage and if the issues with the power button and sleeping are gone.

**Comment by raisjn** [comment] 2021-05-03 14:30
@aedelsten no news is good news?

**Comment by aedelsten** [comment] 2021-05-10 20:40
Hi - so, generally speaking turning off the remux power management has stopped the "weird" behavior. Two caveats:
1. I have to remember to switch back to "remarkable" after reading in koreader. I forgot one night and by morning the battery was completely dead (and then I tried to charge it with a crappy little USB charger and it would turn on and the screen remained black and I freaked out and thought it'd been bricked).
2. If I have been using the RM2, then use remux and read in koreader, then go back and use the rm2 for a while, then when I go back into koreader, koreader has "gone to sleep" and has "device suspended" in the middle of its screen and you have to tap the power button to "wake" koreader. I've not found a way to turn off the koreader power management but, it's actually probably for the best as it makes sure that koreader sleeps when not in the foreground.

So, yes, I think you can close this issue out but maybe make a point in the readme to turn off power management.

**Comment by Witos** [comment] 2021-05-31 11:05
@aedelsten 
In order to turn power mgmt in KOReader off:
1. Pick third menu icon from the left -> More Tools -> Plugin management -> Turn "Auto suspend" off, restart
2. Comment the line in /opt/koreader/frontend/device/remarkable/event_map.lua:
` return {
      [102] = "Home",
      [105] = "LPgBack",
      [106] = "RPgFwd",
       --    [116] = "Power",
  }`

**Comment by Dal78** [comment] 2021-07-02 11:38
Hi,

I'm not sure if I'm thread hijacking here.

I'm running the latest version of RM software on RM2 with the testing branch of toltec.

I have disabled remux power management with the config file.

When i sleep the device if i left swipe up remux still loads.  Is this correct behaviour?  Is it eating up the battery keeping the capacity layer active?

**Comment by raisjn** [comment] 2021-07-02 15:19
> When i sleep the device if i left swipe up remux still loads. Is this correct behaviour? Is it eating up the battery keeping the capacity layer active?



try keeping your usb cable plugged into the device and monitoring the network status of the rM. it usually doesn't immediately turn off but takes a minute (or a few). you might need to wait 5 - 10 minutes before checking if the swipe does or doesn't work. 

someone reported similar behavior on RM1: https://github.com/rmkit-dev/rmkit/issues/43#issuecomment-782732787 and my investigation indicated that it was not a bug but normal (and the power will go off in a minute or so)

**Comment by raisjn** [comment] 2021-07-02 15:19
FWIW: i have remux on rM2 and the power usage is fine (multiple weeks in idle)

**Comment by raisjn** [comment] 2021-12-13 22:25
closing out for now, please re-open if its still an issue

**Closed by raisjn** 2021-12-13 22:25 UTC
