### ISSUE TITLE
[remux] When using with ddvk's remarkable-hacks, the screen will refresh and sometimes launch an app

### ISSUE THREAD

**Issue by nullstalgia** [rmkit-dev/rmkit#44] opened 2021-01-14 11:32 UTC
https://streamable.com/ws4ep2

(sorry for background 3d printer noise)

Sometimes, when my hand and pen touch at the same time (which is common when writing), part of the screen will refresh, and sometimes will launch an app from Remux without the menu having time to show.

It looks like Remux is listening to the input events and somehow my marker and hand equal a home button hold?

I had weird issues with Oxide as well, where after enabling Zen Mode in `remarkable-hacks` by pressing L and R simultaneously, pressing any of the physical buttons would act as if I was holding it down, regardless of how long I actually touched it.

[Issue for remarkable-hacks](https://github.com/ddvk/remarkable-hacks/issues/188)

**Comment by raisjn** [comment] 2021-01-14 11:55
can you check with version 0.1.5 in toltec stable? it's possible remux thinks the three finger tap is being hit and launching itself or the slide action is happening

I'll be adding a config file that lets you turn off the swipe and tap gesture to launch remux

**Comment by nullstalgia** [comment] 2021-01-14 11:56
As far as I can tell, that's the one I've been using. Got it with the
default stable branch of toltec

**Comment by raisjn** [comment] 2021-01-14 12:03
can you try out https://raisjn.net/remux.no_gestures binary and save it as /opt/bin/remux (and make sure to `chmod +x /opt/bin/remux` after placing it.) it's a build without any of the gestures enabled. if remux still launches by accident, it means that there is an issue with buttons. if it doesn't, it means that the issue is in the gestures.

you can test if gestures are enabled by doing a three finger tap on the screen. 

`opkg info remux` should show 0.1.5 (which hit stable yesterday)

**Comment by nullstalgia** [comment] 2021-01-14 12:14
Yup, that fixed it!

And yeah, 0.1.5-1.

**Comment by raisjn** [comment] 2021-01-14 12:21
as a favor, can you check if https://raisjn.net/remux.no_swipe fixes it too? (i'm trying to determine if its the swipe or tap gesture that is accidentally triggering). (also need to chmod +x it)

**Comment by nullstalgia** [comment] 2021-01-14 12:31
Seems to have also fixed it, but now the recent files dialog from the hack shows up now consistently, when before it would only show up sometimes. So, improvement if you like it I guess, haha. I don't mind it, and this seems more in line with intended behavior.

**Comment by raisjn** [comment] 2021-01-14 12:32
great, thank you! 

recently, added a 'three finger tap' gesture for bringing up remux - just tap with three fingers, it should launch faster than holding middle button and will not bring up the ddvk rmhack recent files menu.

**Comment by nullstalgia** [comment] 2021-01-14 13:18
Hopefully you make it optional, there's a lot of stuff that also use that
shortcut. :)

**Comment by raisjn** [comment] 2021-01-14 23:21
yes, it's configurable (i agree - should make it easy for everyone to customize) - the details are in remux's README.md

**Comment by nullstalgia** [comment] 2021-01-14 23:32
Much appreciated! Thanks for the fast replies and good work. I'll let you
know if I find any other issues/have any suggestions. :)

**Comment by Pemo11235** [comment] 2021-01-23 11:53
I had same issue. And no-swipe actually not work for me(it collide with rm hacks), while no-gesture solved.
Im not sure, now, how to acces to remux menu (rm2).Can you help me please?

**Comment by raisjn** [comment] 2021-01-23 12:51
@pemo11234 you can install the remux in testing (https://toltec-dev.org/testing/remux_0.1.7-3_armv7-3.2.ipk), then following the README instructions for configuring gestures. alternatively, you can install the remux binary from build.rmkit.dev/master/latest/files/

by default, swipe up the left or right side of the display to launch remux on rM2. you can hold the middle button on rM1 to also launch.

**Comment by notDavid** [comment] 2021-01-23 18:06
Just FYI: i'm seeing the same issue on my rm2 with remux sometimes "flashing/refreshing" the screen, pen strokes not drawing properly for a second and/or suddenly showing the remux menu.

**Comment by raisjn** [comment] 2021-01-23 18:09
please consider using the version from testing, linked above. if it repros with that, let me know

**Comment by nullstalgia** [comment] 2021-01-23 19:22
Tested out `testing` on my rM1 with back and launch gestures blanked

`/home/root/.config/remux/remux.conf`

```
launch_gesture=
back_gesture=
```

All is well so far. Holding Middle shows Recent Files from the hack and Remux

**Comment by Pemo11235** [comment] 2021-01-23 21:20
I installed testing version from toltec, and actually works for me. I also kept empty the conf file. 
So now I use swipe up on right to access to menu. 

Thanks for answers !

OT:  I fell in love for Harmony,

**Comment by raisjn** [comment] 2021-01-29 14:22
this is fixed in stable, but the version of remux (0.1.7) with config hasn't landed in stable yet. closing since this issue is about the overall bug and that's fixed in stable

**Closed by raisjn** 2021-01-29 14:22 UTC
